server:
  port: 7071

spring:
  application:
    name: JRTP701-ApplicationRegistrationService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
ar:
  ssa-web:
    url: http://localhost:9090/find/{ssn}
  state: california
